FROM ubuntu:24.04

LABEL \
    description="Don't Starve Together dedicated server" \
    source="https://github.com/mathielo/dst-dedicated-server"

RUN apt update && apt upgrade -y && apt install zip unzip wget build-essential pkg-config g++ cmake git curl python3 ninja-build -y \
    && wget -qO vcpkg.tar.gz https://github.com/microsoft/vcpkg/archive/master.tar.gz\
    && mkdir /opt/vcpkg && tar xf vcpkg.tar.gz --strip-components=1 -C /opt/vcpkg &&\
    /opt/vcpkg/bootstrap-vcpkg.sh &&\
    ln -s /opt/vcpkg/vcpkg /usr/local/bin/vcpkg &&\
    vcpkg version
# Create specific user to run DST server
WORKDIR /root
RUN set -x && \
    dpkg --add-architecture i386 && \
    apt-get update && apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget ca-certificates libgcc1 lib32stdc++6 libcurl4-gnutls-dev:i386 && \
    # Download Steam CMD (https://developer.valvesoftware.com/wiki/SteamCMD#Downloading_SteamCMD)
    wget -q -O - "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - && \
    # Cleanup
    apt-get autoremove --purge -y wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    
RUN mkdir -p /root/.klei/DoNotStarveTogether /root/server_dst/mods

# Install Don't Starve Together
RUN /root/steamcmd.sh \
    +@ShutdownOnFailedCommand 1 \
    +@NoPromptForPassword 1 \
    +force_install_dir /root/server_dst \
    +login anonymous \
    +app_update 343050 validate \
    +quit

COPY docker/DSTClusterConfig /root/.klei/DoNotStarveTogether/DSTWhalesCluster/