#pragma once

#define LUA_API_DEFINES(_)   \
    _(lua_newstate)          \
    _(lua_close)             \
    _(lua_newthread)         \
    _(lua_atpanic)           \
    _(lua_gettop)            \
    _(lua_settop)            \
    _(lua_pushvalue)         \
    _(lua_remove)            \
    _(lua_insert)            \
    _(lua_replace)           \
    _(lua_checkstack)        \
    _(lua_xmove)             \
    _(lua_isnumber)          \
    _(lua_isstring)          \
    _(lua_iscfunction)       \
    _(lua_isuserdata)        \
    _(lua_type)              \
    _(lua_typename)          \
    _(lua_equal)             \
    _(lua_rawequal)          \
    _(lua_lessthan)          \
    _(lua_tonumber)          \
    _(lua_tointeger)         \
    _(lua_toboolean)         \
    _(lua_tolstring)         \
    _(lua_objlen)            \
    _(lua_tocfunction)       \
    _(lua_touserdata)        \
    _(lua_tothread)          \
    _(lua_topointer)         \
    _(lua_pushnil)           \
    _(lua_pushnumber)        \
    _(lua_pushinteger)       \
    _(lua_pushlstring)       \
    _(lua_pushstring)        \
    _(lua_pushvfstring)      \
    _(lua_pushfstring)       \
    _(lua_pushcclosure)      \
    _(lua_pushboolean)       \
    _(lua_pushlightuserdata) \
    _(lua_pushthread)        \
    _(lua_gettable)          \
    _(lua_getfield)          \
    _(lua_rawget)            \
    _(lua_rawgeti)           \
    _(lua_createtable)       \
    _(lua_newuserdata)       \
    _(lua_getmetatable)      \
    _(lua_getfenv)           \
    _(lua_settable)          \
    _(lua_setfield)          \
    _(lua_rawset)            \
    _(lua_rawseti)           \
    _(lua_setmetatable)      \
    _(lua_setfenv)           \
    _(lua_call)              \
    _(lua_pcall)             \
    _(lua_cpcall)            \
    _(lua_load)              \
    _(lua_dump)              \
    _(lua_yield)             \
    _(lua_resume)            \
    _(lua_status)            \
    _(lua_gc)                \
    _(lua_error)             \
    _(lua_next)              \
    _(lua_concat)            \
    _(lua_getallocf)         \
    _(lua_setallocf)         \
    _(lua_setlevel)          \
    _(lua_getstack)          \
    _(lua_getinfo)           \
    _(lua_getlocal)          \
    _(lua_setlocal)          \
    _(lua_getupvalue)        \
    _(lua_setupvalue)        \
    _(lua_sethook)           \
    _(lua_gethook)           \
    _(lua_gethookmask)       \
    _(lua_gethookcount)      \
    _(luaL_openlib)          \
    _(luaL_register)         \
    _(luaL_getmetafield)     \
    _(luaL_callmeta)         \
    _(luaL_typerror)         \
    _(luaL_argerror)         \
    _(luaL_checklstring)     \
    _(luaL_optlstring)       \
    _(luaL_checknumber)      \
    _(luaL_optnumber)        \
    _(luaL_checkinteger)     \
    _(luaL_optinteger)       \
    _(luaL_optboolean)       \
    _(luaL_checkboolean)     \
    _(luaL_checkstack)       \
    _(luaL_checktype)        \
    _(luaL_checkany)         \
    _(luaL_newmetatable)     \
    _(luaL_checkudata)       \
    _(luaL_where)            \
    _(luaL_error)            \
    _(luaL_checkoption)      \
    _(luaL_ref)              \
    _(luaL_unref)            \
    _(luaL_loadfile)         \
    _(luaL_loadbuffer)       \
    _(luaL_loadstring)       \
    _(luaL_newstate)         \
    _(luaL_gsub)             \
    _(luaL_findtable)        \
    _(luaL_buffinit)         \
    _(luaL_prepbuffer)       \
    _(luaL_addlstring)       \
    _(luaL_addstring)        \
    _(luaL_addvalue)         \
    _(luaL_pushresult)       \
    _(luaL_openlibs)         \
    _(luaopen_base)          \
    _(luaopen_debug)         \
    _(luaopen_io)            \
    _(luaopen_math)          \
    _(luaopen_os)            \
    _(luaopen_package)       \
    _(luaopen_string)        \
    _(luaopen_table)

#define LUA51_API_DEFINES(_) LUA_API_DEFINES(_)
#define LUAJIT_API_DEFINES(_) \
    _(luaopen_bit)            \
    _(luaopen_jit)            \
    _(luaopen_ffi)            \
    _(luaopen_string_buffer)

#define LUAJIT_API_DEFINES_5_2(_) \
    _(luaL_fileresult)            \
    _(luaL_execresult)            \
    _(luaL_loadfilex)             \
    _(luaL_loadbufferx)           \
    _(luaL_traceback)             \
    _(luaL_setfuncs)              \
    _(luaL_pushmodule)            \
    _(luaL_testudata)             \
    _(luaL_setmetatable)          \
    _(lua_upvalueid)              \
    _(lua_upvaluejoin)            \
    _(lua_loadx)                  \
    _(lua_version)                \
    _(lua_copy)                   \
    _(lua_tonumberx)              \
    _(lua_tointegerx)

#define LUAJIT_API_DEFINES_5_3(_) \
    _(lua_isyieldable)
