#!/usr/bin/env python3

import argparse
from collections.abc import Callable
import json
import re
import sys
from pathlib import Path

from steam_env import detect_steam_root, find_game_by_appid, steam_library_paths


DEFAULT_APPID = "322330"


def _replace_once(
    text: str,
    pattern: str,
    replacement: str | Callable[[re.Match[str]], str],
    description: str,
) -> str:
    new_text, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Failed to update {description}: expected 1 match, got {count}.")
    return new_text


def _write_if_changed(path: Path, content: str) -> bool:
    original = path.read_text(encoding="utf-8") if path.exists() else None
    if original == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def update_game_dir_cmake(game_dir_cmake_path: Path, game_dir: Path) -> bool:
    game_dir_text = game_dir.as_posix()
    generated = (
        "# Generated by tools/update_steam_paths.py. Do not edit manually.\n"
        f'set(GAME_DIR "{game_dir_text}")\n'
    )
    return _write_if_changed(game_dir_cmake_path, generated)


def update_settings(settings_path: Path, steamapps_dir: Path) -> bool:
    text = settings_path.read_text(encoding="utf-8")
    steamapps_text = json.dumps(str(steamapps_dir))[1:-1]
    updated = _replace_once(
        text,
        r'(^\s*"steam\.root":\s*")[^"]*(",\s*$)',
        lambda current: f'{current.group(1)}{steamapps_text}{current.group(2)}',
        f"steam.root in {settings_path}",
    )
    return _write_if_changed(settings_path, updated)


def resolve_paths(workspace_root: Path, appid: str, steam_root_arg: str | None) -> tuple[Path, Path]:
    steam_root = detect_steam_root(steam_root_arg)
    if steam_root is None:
        raise RuntimeError("Steam root not found. Use --steam-root to specify it explicitly.")

    libraries = steam_library_paths(steam_root)
    game_dir = find_game_by_appid(libraries, appid)
    if game_dir is None:
        raise RuntimeError(f"Steam app {appid} is not installed in the detected Steam libraries.")

    steamapps_dir = game_dir.parent.parent
    if steamapps_dir.name.casefold() != "steamapps":
        raise RuntimeError(f"Unexpected game path layout: {game_dir}")

    return steamapps_dir.resolve(), game_dir.resolve()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate cmake/GameDir.cmake and update .vscode/settings.json with detected Steam paths."
    )
    parser.add_argument(
        "--workspace-root",
        default=Path(__file__).resolve().parents[1],
        type=Path,
        help="Workspace root containing .vscode/settings.json and the generated cmake/GameDir.cmake target",
    )
    parser.add_argument(
        "--game-dir-cmake",
        default=None,
        type=Path,
        help="Path to the generated CMake file that overrides GAME_DIR (defaults to <workspace-root>/cmake/GameDir.cmake)",
    )
    parser.add_argument("--steam-root", default=None, help="Override Steam root directory")
    parser.add_argument("--appid", default=DEFAULT_APPID, help="Steam app id to locate")
    parser.add_argument("--dry-run", action="store_true", help="Show resolved paths without editing files")
    args = parser.parse_args()

    workspace_root = args.workspace_root.resolve()
    game_dir_cmake_path = (
        args.game_dir_cmake.resolve()
        if args.game_dir_cmake is not None
        else workspace_root / "cmake" / "GameDir.cmake"
    )
    settings_path = workspace_root / ".vscode" / "settings.json"

    if not settings_path.exists():
        raise RuntimeError(f"Missing file: {settings_path}")

    steamapps_dir, game_dir = resolve_paths(workspace_root, str(args.appid), args.steam_root)

    print(f"Resolved steamapps: {steamapps_dir}")
    print(f"Resolved game dir: {game_dir}")

    if args.dry_run:
        return 0

    cmake_changed = update_game_dir_cmake(game_dir_cmake_path, game_dir)
    settings_changed = update_settings(settings_path, steamapps_dir)

    print(f"Updated {game_dir_cmake_path}: {'yes' if cmake_changed else 'no change'}")
    print(f"Updated {settings_path}: {'yes' if settings_changed else 'no change'}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)